# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview', '0004_auto_20170301_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
