# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview', '0005_auto_20170301_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
