# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview', '0010_auto_20170304_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
